name: 'test-split-action--huyntq'
description: 'Provide a description here'
author: 'Huyntq'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  TOKEN: 
    description: "Github token"
    required: true
  DIRECTORY: 
    description: "Directory to search for test files"
  RESULT_NAME:
    description: "Name of the result file"

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
